// Comprehensive test data for HanBuy platform
// Use this data to test all features and verify functionality

import type {
  User,
  Product,
  Box,
  Invoice,
  TrackingEvent,
  Address,
} from "@/types";
import type {
  Order,
  QRPayment,
} from "@/types/orders";
import type {
  ManilaReceiving,
  ConsolidationBox,
  CourierShipment,
} from "@/types/fulfillment";

// Test Users
export const testUsers: User[] = [
  {
    id: "user-test-customer-1",
    email: "customer1@test.com",
    name: "Maria Santos",
    phone: "+63 912 345 6789",
    address: {
      street: "123 Rizal Street",
      city: "Makati",
      province: "Metro Manila",
      zipCode: "1200",
      country: "Philippines",
    },
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "user-test-customer-2",
    email: "customer2@test.com",
    name: "Juan Dela Cruz",
    phone: "+63 923 456 7890",
    address: {
      street: "456 EDSA",
      city: "Quezon City",
      province: "Metro Manila",
      zipCode: "1100",
      country: "Philippines",
    },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "user-test-customer-3",
    email: "customer3@test.com",
    name: "Ana Garcia",
    phone: "+63 934 567 8901",
    address: {
      street: "789 Ayala Avenue",
      city: "BGC",
      province: "Taguig",
      zipCode: "1634",
      country: "Philippines",
    },
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-10"),
  },
  {
    id: "user-test-admin",
    email: "admin@hanbuy.com",
    name: "Admin User",
    phone: "+63 900 000 0000",
    address: {
      street: "Manila Office",
      city: "Manila",
      province: "Metro Manila",
      zipCode: "1000",
      country: "Philippines",
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

// Test Products (Mix of Onhand and Pre-Order)
export const testProducts: Product[] = [
  // Onhand Products
  {
    id: "prod-test-onhand-1",
    name: "COSRX Advanced Snail 96 Mucin Power Essence",
    description: "96% snail secretion filtrate essence for skin repair",
    price: 25000,
    currency: "KRW",
    images: ["https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500"],
    category: "skincare",
    brand: "COSRX",
    sku: "COSRX-SNAIL-96",
    stock: 50,
    weight: 0.1,
    dimensions: { length: 15, width: 5, height: 20 },
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-12-20"),
  },
  {
    id: "prod-test-onhand-2",
    name: "Beauty of Joseon Relief Sun SPF50+",
    description: "Rice extract sunscreen for sensitive skin",
    price: 18000,
    currency: "KRW",
    images: ["https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500"],
    category: "skincare",
    brand: "Beauty of Joseon",
    sku: "BOJ-SUN-50",
    stock: 75,
    weight: 0.08,
    dimensions: { length: 12, width: 4, height: 18 },
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-12-20"),
  },
  {
    id: "prod-test-onhand-3",
    name: "Samyang Buldak Hot Chicken Ramen (5 Pack)",
    description: "Extremely spicy Korean instant noodles",
    price: 12000,
    currency: "KRW",
    images: ["https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500"],
    category: "food",
    brand: "Samyang",
    sku: "SAM-BULDAK-5",
    stock: 100,
    weight: 0.5,
    dimensions: { length: 25, width: 20, height: 15 },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-12-20"),
  },
  // Pre-Order Products
  {
    id: "prod-test-preorder-1",
    name: "Limited Edition K-Beauty Set 2025",
    description: "Exclusive pre-order K-beauty collection",
    price: 85000,
    currency: "KRW",
    images: ["https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500"],
    category: "skincare",
    brand: "K-Beauty",
    sku: "KB-LIMITED-2025",
    stock: 0, // Pre-order, no stock yet
    weight: 0.5,
    dimensions: { length: 20, width: 15, height: 25 },
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2024-12-20"),
  },
  {
    id: "prod-test-preorder-2",
    name: "New Year Korean Snack Box",
    description: "Special edition Korean snacks for New Year",
    price: 35000,
    currency: "KRW",
    images: ["https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500"],
    category: "food",
    brand: "Korean Snacks",
    sku: "KS-NY-2025",
    stock: 0,
    weight: 1.2,
    dimensions: { length: 30, width: 25, height: 20 },
    createdAt: new Date("2024-12-05"),
    updatedAt: new Date("2024-12-20"),
  },
];

// Test Orders - Covering all scenarios
export const testOrders: Order[] = [
  // Order 1: Onhand items, Full payment, Solo box, Delivered
  {
    id: "order-test-1",
    userId: "user-test-customer-1",
    orderNumber: "ORD-2024-001",
    items: [
      {
        id: "item-1",
        productId: "prod-test-onhand-1",
        productName: "COSRX Advanced Snail 96 Mucin Power Essence",
        productType: "onhand",
        quantity: 2,
        unitPrice: 25000,
        total: 50000,
        imageUrl: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500",
      },
      {
        id: "item-2",
        productId: "prod-test-onhand-2",
        productName: "Beauty of Joseon Relief Sun SPF50+",
        productType: "onhand",
        quantity: 1,
        unitPrice: 18000,
        total: 18000,
      },
    ],
    subtotal: 68000,
    isf: 1500, // International Service Fee
    lsf: 800, // Local Service Fee (solo)
    shippingFee: 2300,
    soloShippingFee: 2300,
    sharedShippingFee: 1500,
    boxTypePreference: "solo",
    total: 70300,
    currency: "PHP",
    status: "delivered",
    paymentStatus: "paid",
    paymentType: "full",
    paymentMethod: {
      type: "qr_code",
      bank: "GCASH",
      qrCode: "qr-test-gcash-001",
    },
    shippingAddress: testUsers[0].address!,
    fulfillmentStatus: "delivered",
    packedAt: new Date("2024-12-10"),
    shippedToManilaAt: new Date("2024-12-12"),
    receivedAtManilaAt: new Date("2024-12-15"),
    boxId: "box-test-1",
    phCourierTrackingNumber: "JNT123456789",
    phCourierName: "J&T Express",
    createdAt: new Date("2024-12-05"),
    updatedAt: new Date("2024-12-20"),
    paidAt: new Date("2024-12-05"),
  },
  // Order 2: Pre-order items, Downpayment, Shared box, In transit
  {
    id: "order-test-2",
    userId: "user-test-customer-1",
    orderNumber: "ORD-2024-002",
    items: [
      {
        id: "item-3",
        productId: "prod-test-preorder-1",
        productName: "Limited Edition K-Beauty Set 2025",
        productType: "preorder",
        quantity: 1,
        unitPrice: 85000,
        total: 85000,
        preorderReleaseDate: new Date("2025-01-15"),
      },
    ],
    subtotal: 85000,
    isf: 2000,
    lsf: 500, // Reduced for shared box
    shippingFee: 2500,
    soloShippingFee: 2800,
    sharedShippingFee: 1500,
    boxTypePreference: "shared",
    total: 87000,
    currency: "PHP",
    status: "in_transit_to_manila",
    paymentStatus: "partial",
    paymentType: "downpayment",
    downpaymentAmount: 43500, // 50% downpayment
    downpaymentPaid: 43500,
    balance: 43500,
    paymentMethod: {
      type: "qr_code",
      bank: "MAYA",
      qrCode: "qr-test-maya-001",
    },
    shippingAddress: testUsers[0].address!,
    fulfillmentStatus: "in_transit_to_manila",
    packedAt: new Date("2024-12-25"),
    shippedToManilaAt: new Date("2024-12-26"),
    createdAt: new Date("2024-12-20"),
    updatedAt: new Date("2024-12-26"),
    paidAt: new Date("2024-12-20"),
  },
  // Order 3: Mixed items (onhand + preorder), Full payment, Shared box, Received at Manila
  {
    id: "order-test-3",
    userId: "user-test-customer-2",
    orderNumber: "ORD-2024-003",
    items: [
      {
        id: "item-4",
        productId: "prod-test-onhand-3",
        productName: "Samyang Buldak Hot Chicken Ramen (5 Pack)",
        productType: "onhand",
        quantity: 3,
        unitPrice: 12000,
        total: 36000,
      },
      {
        id: "item-5",
        productId: "prod-test-preorder-2",
        productName: "New Year Korean Snack Box",
        productType: "preorder",
        quantity: 1,
        unitPrice: 35000,
        total: 35000,
        preorderReleaseDate: new Date("2025-01-10"),
      },
    ],
    subtotal: 71000,
    isf: 1800,
    lsf: 500,
    shippingFee: 2300,
    soloShippingFee: 2500,
    sharedShippingFee: 1500,
    boxTypePreference: "shared",
    total: 72800,
    currency: "PHP",
    status: "received_at_manila",
    paymentStatus: "paid",
    paymentType: "full",
    paymentMethod: {
      type: "qr_code",
      bank: "BPI",
      qrCode: "qr-test-bpi-001",
    },
    shippingAddress: testUsers[1].address!,
    fulfillmentStatus: "received_at_manila",
    packedAt: new Date("2024-12-22"),
    shippedToManilaAt: new Date("2024-12-24"),
    receivedAtManilaAt: new Date("2024-12-27"),
    createdAt: new Date("2024-12-18"),
    updatedAt: new Date("2024-12-27"),
    paidAt: new Date("2024-12-18"),
  },
  // Order 4: Onhand items, Pending payment, Solo box
  {
    id: "order-test-4",
    userId: "user-test-customer-3",
    orderNumber: "ORD-2024-004",
    items: [
      {
        id: "item-6",
        productId: "prod-test-onhand-1",
        productName: "COSRX Advanced Snail 96 Mucin Power Essence",
        productType: "onhand",
        quantity: 1,
        unitPrice: 25000,
        total: 25000,
      },
    ],
    subtotal: 25000,
    isf: 1000,
    lsf: 800,
    shippingFee: 1800,
    soloShippingFee: 1800,
    sharedShippingFee: 1000,
    boxTypePreference: "solo",
    total: 26800,
    currency: "PHP",
    status: "pending",
    paymentStatus: "pending",
    paymentType: "full",
    paymentMethod: {
      type: "qr_code",
      bank: "GOTYME",
      qrCode: "qr-test-gotyme-001",
    },
    shippingAddress: testUsers[2].address!,
    fulfillmentStatus: "pending_packing",
    createdAt: new Date("2024-12-28"),
    updatedAt: new Date("2024-12-28"),
  },
  // Order 5: Pre-order only, Downpayment paid, Waiting for release
  {
    id: "order-test-5",
    userId: "user-test-customer-2",
    orderNumber: "ORD-2024-005",
    items: [
      {
        id: "item-7",
        productId: "prod-test-preorder-1",
        productName: "Limited Edition K-Beauty Set 2025",
        productType: "preorder",
        quantity: 2,
        unitPrice: 85000,
        total: 170000,
        preorderReleaseDate: new Date("2025-01-15"),
      },
    ],
    subtotal: 170000,
    isf: 3500,
    lsf: 1200,
    shippingFee: 4700,
    soloShippingFee: 5000,
    sharedShippingFee: 3000,
    boxTypePreference: "solo",
    total: 173500,
    currency: "PHP",
    status: "confirmed",
    paymentStatus: "partial",
    paymentType: "downpayment",
    downpaymentAmount: 86750,
    downpaymentPaid: 86750,
    balance: 86750,
    paymentMethod: {
      type: "qr_code",
      bank: "BDO",
      qrCode: "qr-test-bdo-001",
    },
    shippingAddress: testUsers[1].address!,
    fulfillmentStatus: "pending_packing",
    createdAt: new Date("2024-12-15"),
    updatedAt: new Date("2024-12-15"),
    paidAt: new Date("2024-12-15"),
  },
];

// Test QR Payments
export const testQRPayments: QRPayment[] = [
  {
    id: "qr-test-1",
    orderId: "order-test-1",
    amount: 70300,
    currency: "PHP",
    bank: "GCASH",
    qrCode: "qr-test-gcash-001",
    qrCodeData: "00020101021243200016COM.PHILIPPINEQR01162110009GCASH.COM0120200000000000000000040600010303015204000053036085405703.005802PH5920HANBUY MANILA OFFICE6009MANILA6104100016244051012345678903060017040819006304ABCD",
    paymentType: "full",
    expiresAt: new Date("2025-01-05"),
    paid: true,
    paidAt: new Date("2024-12-05"),
    verified: true,
    verifiedAt: new Date("2024-12-05"),
    verifiedBy: "user-test-admin",
    createdAt: new Date("2024-12-05"),
  },
  {
    id: "qr-test-2",
    orderId: "order-test-2",
    amount: 43500,
    currency: "PHP",
    bank: "MAYA",
    qrCode: "qr-test-maya-001",
    qrCodeData: "00020101021243200016COM.PHILIPPINEQR01162110009MAYA.PAY.PH0120200000000000000000040600010303015204000053036085405435.005802PH5920HANBUY MANILA OFFICE6009MANILA6104100016244051012345678913060017040819006304ABCD",
    paymentType: "downpayment",
    expiresAt: new Date("2025-01-01"),
    paid: true,
    paidAt: new Date("2024-12-20"),
    verified: true,
    verifiedAt: new Date("2024-12-20"),
    verifiedBy: "user-test-admin",
    createdAt: new Date("2024-12-20"),
  },
  {
    id: "qr-test-4",
    orderId: "order-test-4",
    amount: 26800,
    currency: "PHP",
    bank: "GOTYME",
    qrCode: "qr-test-gotyme-001",
    qrCodeData: "00020101021243200016COM.PHILIPPINEQR01162110009GOTYME.COM0120200000000000000000040600010303015204000053036085405268.005802PH5920HANBUY MANILA OFFICE6009MANILA6104100016244051012345678923060017040819006304ABCD",
    paymentType: "full",
    expiresAt: new Date("2025-01-05"),
    paid: false,
    verified: false,
    createdAt: new Date("2024-12-28"),
  },
];

// Test Boxes
export const testBoxes: Box[] = [
  {
    id: "box-test-1",
    userId: "user-test-customer-1",
    boxNumber: "HB-2024-001",
    status: "delivered",
    items: [
      {
        id: "box-item-1",
        boxId: "box-test-1",
        name: "COSRX Advanced Snail 96 Mucin Power Essence",
        quantity: 2,
        price: 25000,
        currency: "KRW",
        weight: 0.2,
        dimensions: { length: 15, width: 5, height: 20 },
        sku: "COSRX-SNAIL-96",
        createdAt: new Date("2024-12-10"),
      },
      {
        id: "box-item-2",
        boxId: "box-test-1",
        name: "Beauty of Joseon Relief Sun SPF50+",
        quantity: 1,
        price: 18000,
        currency: "KRW",
        weight: 0.08,
        dimensions: { length: 12, width: 4, height: 18 },
        sku: "BOJ-SUN-50",
        createdAt: new Date("2024-12-10"),
      },
    ],
    currentLocation: "Delivered to customer",
    trackingHistory: [
      {
        id: "track-1",
        boxId: "box-test-1",
        status: "in_warehouse",
        location: "Korea Warehouse",
        description: "Box created and items packed",
        timestamp: new Date("2024-12-10"),
      },
      {
        id: "track-2",
        boxId: "box-test-1",
        status: "in_transit",
        location: "In Transit to Philippines",
        description: "Shipped from Korea",
        timestamp: new Date("2024-12-12"),
      },
      {
        id: "track-3",
        boxId: "box-test-1",
        status: "at_ph_hub",
        location: "Manila Office",
        description: "Received at Manila office",
        timestamp: new Date("2024-12-15"),
      },
      {
        id: "track-4",
        boxId: "box-test-1",
        status: "out_for_delivery",
        location: "J&T Express Distribution Center",
        description: "Out for delivery",
        timestamp: new Date("2024-12-18"),
      },
      {
        id: "track-5",
        boxId: "box-test-1",
        status: "delivered",
        location: "Makati, Metro Manila",
        description: "Delivered to customer",
        timestamp: new Date("2024-12-20"),
      },
    ],
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2024-12-20"),
    estimatedDelivery: new Date("2024-12-20"),
  },
];

// Test Invoices
export const testInvoices: Invoice[] = [
  {
    id: "inv-test-1",
    userId: "user-test-customer-1",
    boxId: "box-test-1",
    invoiceNumber: "INV-2024-001",
    items: [
      {
        id: "inv-item-1",
        description: "COSRX Advanced Snail 96 Mucin Power Essence x2",
        quantity: 2,
        unitPrice: 1050,
        total: 2100,
      },
      {
        id: "inv-item-2",
        description: "Beauty of Joseon Relief Sun SPF50+ x1",
        quantity: 1,
        unitPrice: 756,
        total: 756,
      },
      {
        id: "inv-item-3",
        description: "International Service Fee (ISF)",
        quantity: 1,
        unitPrice: 1500,
        total: 1500,
      },
      {
        id: "inv-item-4",
        description: "Local Service Fee (LSF) - Solo Box",
        quantity: 1,
        unitPrice: 800,
        total: 800,
      },
    ],
    subtotal: 2856,
    shippingFee: 2300,
    customsFee: 0,
    total: 7030,
    currency: "PHP",
    status: "paid",
    dueDate: new Date("2024-12-12"),
    paidAt: new Date("2024-12-05"),
    paymentMethod: "GCASH QR Code",
    createdAt: new Date("2024-12-05"),
    updatedAt: new Date("2024-12-05"),
  },
];

// Test Manila Receiving
export const testManilaReceiving: ManilaReceiving[] = [
  {
    id: "receiving-test-1",
    orderId: "order-test-3",
    orderNumber: "ORD-2024-003",
    trackingNumber: "KR-EXPRESS-123456",
    items: [
      {
        id: "rec-item-1",
        orderItemId: "item-4",
        productId: "prod-test-onhand-3",
        productName: "Samyang Buldak Hot Chicken Ramen (5 Pack)",
        quantity: 3,
        receivedQuantity: 3,
        condition: "good",
      },
      {
        id: "rec-item-2",
        orderItemId: "item-5",
        productId: "prod-test-preorder-2",
        productName: "New Year Korean Snack Box",
        quantity: 1,
        receivedQuantity: 1,
        condition: "good",
      },
    ],
    receivedBy: "user-test-admin",
    receivedAt: new Date("2024-12-27"),
    condition: "good",
    status: "received",
  },
];

// Test Consolidation Boxes
export const testConsolidationBoxes: ConsolidationBox[] = [
  {
    id: "consolidation-box-1",
    boxNumber: "CONS-2024-001",
    boxType: "shared",
    orders: ["order-test-2", "order-test-3"],
    customers: [
      {
        orderId: "order-test-2",
        userId: "user-test-customer-1",
        customerName: "Maria Santos",
        customerEmail: "customer1@test.com",
        customerPhone: "+63 912 345 6789",
        shippingAddress: testUsers[0].address!,
        items: [
          {
            id: "cons-item-1",
            orderId: "order-test-2",
            orderItemId: "item-3",
            productId: "prod-test-preorder-1",
            productName: "Limited Edition K-Beauty Set 2025",
            quantity: 1,
            weight: 0.5,
            dimensions: { length: 20, width: 15, height: 25 },
          },
        ],
      },
      {
        orderId: "order-test-3",
        userId: "user-test-customer-2",
        customerName: "Juan Dela Cruz",
        customerEmail: "customer2@test.com",
        customerPhone: "+63 923 456 7890",
        shippingAddress: testUsers[1].address!,
        items: [
          {
            id: "cons-item-2",
            orderId: "order-test-3",
            orderItemId: "item-4",
            productId: "prod-test-onhand-3",
            productName: "Samyang Buldak Hot Chicken Ramen (5 Pack)",
            quantity: 3,
            weight: 1.5,
            dimensions: { length: 25, width: 20, height: 15 },
          },
          {
            id: "cons-item-3",
            orderId: "order-test-3",
            orderItemId: "item-5",
            productId: "prod-test-preorder-2",
            productName: "New Year Korean Snack Box",
            quantity: 1,
            weight: 1.2,
            dimensions: { length: 30, width: 25, height: 20 },
          },
        ],
      },
    ],
    items: [
      {
        id: "cons-item-1",
        orderId: "order-test-2",
        orderItemId: "item-3",
        productId: "prod-test-preorder-1",
        productName: "Limited Edition K-Beauty Set 2025",
        quantity: 1,
        weight: 0.5,
        dimensions: { length: 20, width: 15, height: 25 },
      },
      {
        id: "cons-item-2",
        orderId: "order-test-3",
        orderItemId: "item-4",
        productId: "prod-test-onhand-3",
        productName: "Samyang Buldak Hot Chicken Ramen (5 Pack)",
        quantity: 3,
        weight: 1.5,
        dimensions: { length: 25, width: 20, height: 15 },
      },
      {
        id: "cons-item-3",
        orderId: "order-test-3",
        orderItemId: "item-5",
        productId: "prod-test-preorder-2",
        productName: "New Year Korean Snack Box",
        quantity: 1,
        weight: 1.2,
        dimensions: { length: 30, width: 25, height: 20 },
      },
    ],
    ownerPersonalItems: [
      {
        id: "owner-item-1",
        name: "Personal K-Beauty Products",
        description: "Owner's personal skincare items",
        quantity: 5,
        weight: 0.8,
        dimensions: { length: 20, width: 15, height: 25 },
        notes: "Fragile - handle with care",
      },
    ],
    totalWeight: 4.0,
    totalVolume: 0.05,
    status: "closed",
    createdAt: new Date("2024-12-27"),
    closedAt: new Date("2024-12-28"),
  },
];

// Test Courier Shipments
export const testCourierShipments: CourierShipment[] = [
  {
    id: "courier-shipment-1",
    boxId: "box-test-1",
    boxNumber: "HB-2024-001",
    boxType: "solo",
    courierName: "J&T Express",
    trackingNumber: "JNT123456789",
    serviceType: "standard",
    recipientAddress: testUsers[0].address!,
    recipientName: "Maria Santos",
    recipientPhone: "+63 912 345 6789",
    status: "delivered",
    estimatedDelivery: new Date("2024-12-20"),
    actualDelivery: new Date("2024-12-20"),
    createdAt: new Date("2024-12-18"),
    pickedUpAt: new Date("2024-12-18"),
  },
];

// Export all test data in one object for easy access
export const testData = {
  users: testUsers,
  products: testProducts,
  orders: testOrders,
  qrPayments: testQRPayments,
  boxes: testBoxes,
  invoices: testInvoices,
  manilaReceiving: testManilaReceiving,
  consolidationBoxes: testConsolidationBoxes,
  courierShipments: testCourierShipments,
};

// Helper function to get test data for a specific user
export function getTestDataForUser(userId: string) {
  return {
    user: testUsers.find((u) => u.id === userId),
    orders: testOrders.filter((o) => o.userId === userId),
    boxes: testBoxes.filter((b) => b.userId === userId),
    invoices: testInvoices.filter((i) => i.userId === userId),
  };
}

// Test account credentials (for login testing)
export const testAccounts = {
  customers: [
    {
      email: "customer1@test.com",
      password: "test123",
      userId: "user-test-customer-1",
      name: "Maria Santos",
    },
    {
      email: "customer2@test.com",
      password: "test123",
      userId: "user-test-customer-2",
      name: "Juan Dela Cruz",
    },
    {
      email: "customer3@test.com",
      password: "test123",
      userId: "user-test-customer-3",
      name: "Ana Garcia",
    },
  ],
  admin: {
    email: "admin@hanbuy.com",
    password: "admin123",
    userId: "user-test-admin",
    name: "Admin User",
  },
};

